# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_brewwine_divescore_lmessage_storyofbartender_test_testoption_testscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewwine',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storyofbartender',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
